spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
      format_sql: true
  data:
    web:
      pageable:
        default-page-size: 3
        max-page-size: 5
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
